name: CI/CD CinéList

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout du code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          # On précise où se trouve le package-lock.json pour le cache
          cache-dependency-path: vue-project/package-lock.json

      - name: 📦 Installation des dépendances
        working-directory: ./vue-project
        run: npm install

      - name: 🏗️ Build de l'application
        working-directory: ./vue-project
        run: npm run build

      - name: 🚀 Déploiement vers le VPS via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # On prend le dossier dist qui est dans vue-project
          source: "vue-project/dist/*"
          target: "/var/www/cinelist/"
          strip_components: 2 # On enlève "vue-project" et "dist" du chemin final

      - name: 🧹 Nettoyage et Droits sur le VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo chown -R www-data:www-data /var/www/cinelist
            sudo chmod -R 755 /var/www/cinelist
            sudo systemctl reload nginx
